# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  openldap:
    build:
      context: ../image
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ../image
    init: true
    stdin_open: true
    tty: true
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      BITNAMI_DEBUG: true
      LDAP_LOGLEVEL: -1
